# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('ruta_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emprendimiento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('numero_emprendedores', models.CharField(max_length=10)),
                ('numero_colaboradores', models.CharField(max_length=10)),
                ('portafolio', models.CharField(max_length=300)),
                ('clientes', models.CharField(max_length=300)),
                ('vinculo_parquesoft', models.CharField(max_length=10)),
                ('cual_vinculo', models.CharField(max_length=100)),
                ('medio', models.CharField(max_length=100)),
                ('expectativas', models.CharField(max_length=100)),
                ('recibir', models.CharField(max_length=100)),
                ('aporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('tiempo', models.CharField(max_length=50)),
                ('ruta_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechainicio', models.CharField(max_length=50)),
                ('fechafin', models.CharField(max_length=50)),
            ],
        ),
    ]
