# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180111_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ruta_imagen',
            field=models.ImageField(upload_to='imagenes/areas/'),
        ),
    ]
