# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20180115_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
