# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20180115_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
    ]
