# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafoliops',
            name='ruta_imagen',
            field=models.ImageField(upload_to=b''),
        ),
    ]
